"use client";
import "@/styles/globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import MainNavBarLayout from "@/components/Layouts/NavigationBar/MainNavBarLayout"
import MainLayout from "@/components/Layouts/MainLayout";
import Toast from "@/components/Elements/Toast";
import { SessionProvider } from "next-auth/react"
import 'react-toastify/dist/ReactToastify.css';



// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

import { Poppins } from "next/font/google";
import { usePathname } from "next/navigation";
import { Bounce, ToastContainer } from "react-toastify";

const poppins = Poppins({ subsets: ["latin"], style: "normal", weight: "400" });


export default function RootLayout({ children }) {

  const queryClient = new QueryClient({
    defaultOptions: {
      queries: false
    },
  });

  const disableNavigation = ["/login", "/register"]
  const pathname = usePathname()

  const handleLayoutAuth = ({ children }) => {
    const crumbPathname = pathname?.split("/").filter((path) => path !== "")

    const disableBreadcrums = ["/", "/pemesanan", "/riwayat", "/profil"]
    // const breadcrumbs = () => (
    //   <div className="breadcrumbs text-sm mb-2 w-fit p-4">
    //     <ul>
    //       {
    //         crumbPathname?.map((item, i) => (
    //           <li key={i}>
    //             <Link key={i} replace={true} href={`/`}>{item == "lapangan" ? item : item.split("_", item.length).flatMap((item) => item + " ")}</Link>
    //           </li>
    //         ))
    //       }
    //     </ul>
    //   </div>
    // )

    if (pathname === "/login" || pathname === "/register") {
      return { children }
    } else {
      return (
        <>
          <MainLayout>
            {children}
          </MainLayout>
        </>
      )
    }
  }

  return (
    <html lang="en">
      <body className={poppins.className}>
        {/* Next Auth */}
        <SessionProvider>
          {/* Tanstack Query */}
          <QueryClientProvider client={queryClient}>
            {/* Content */}
            <div className="bg-slate-50 flex flex-col scroll-smooth no-scrollbar">

              <MainNavBarLayout>
                {children}
              </MainNavBarLayout>
              {/* Toast */}
              <Toast className="bg-error">Error:</Toast>
            </div>
          </QueryClientProvider>
        </SessionProvider>
        <ToastContainer
          position="bottom-right"
          autoClose={5000}
          hideProgressBar
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
          transition={Bounce}
        />
      </body>
    </html>
  )
}
