"use client";
import "@/styles/globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
// import { usePathname } from "next/navigation";
import MainNavBarLayout from "@/components/Layouts/NavigationBar/MainNavBarLayout"
import MainLayout from "@/components/Layouts/MainLayout";
import Toast from "@/components/Elements/Toast";
import Link from "next/link";
import { SessionProvider } from "next-auth/react"
import Footer from "@/components/Layouts/Footer";


// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

import { Inter } from "next/font/google";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });


export default function RootLayout({ children }) {

  const queryClient = new QueryClient({
    defaultOptions: {
      queries: false
    },
  });
  
  const disableNavigation = ["/login", "/register"]
  const pathname = usePathname()

  const handleLayoutAuth = ({children}) => {
    const crumbPathname = pathname?.split("/").filter((path) => path !== "")

    const disableBreadcrums = ["/", "/pemesanan", "/riwayat", "/profil"]
    // const breadcrumbs = () => (
    //   <div className="breadcrumbs text-sm mb-2 w-fit p-4">
    //     <ul>
    //       {
    //         crumbPathname?.map((item, i) => (
    //           <li key={i}>
    //             <Link key={i} replace={true} href={`/`}>{item == "lapangan" ? item : item.split("_", item.length).flatMap((item) => item + " ")}</Link>
    //           </li>
    //         ))
    //       }
    //     </ul>
    //   </div>
    // )

    if (pathname === "/login" || pathname === "/register") {
      return {children}
    } else {
      return (
        <>
          <MainLayout>
            {children}
          </MainLayout>
        </>
      )
    }
  }
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider>
          {/* Tanstack Query */}
          <QueryClientProvider client={queryClient}>
            {disableNavigation.includes(pathname) ? "" : <MainNavBarLayout />}
            <div className="bg-slate-50">
              <handleLayoutAuth>
                {children}
              </handleLayoutAuth>
              
              <Toast className="bg-error">Error:</Toast>
            </div>
          </QueryClientProvider>
        </SessionProvider>
      </body>
    </html>
  )
}
