"use client"
import "@/styles/globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import MainNavBarLayout from "@/components/Layouts/NavigationBar/MainNavBarLayout"
import { SessionProvider } from "next-auth/react"
import 'react-toastify/dist/ReactToastify.css';



// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

import { Poppins } from "next/font/google";
import { Bounce, ToastContainer } from "react-toastify";

const poppins = Poppins({ subsets: ["latin"], style: "normal", weight: "400" });


export default function RootLayout({ children }) {

  const queryClient = new QueryClient({
    defaultOptions: {
      queries: false
    },
  });

  return (
    <html lang="en">
      <title>Sportfield</title>
      <meta name="viewport" content="width=device-width, initial-scale=1"  />
      <body className={poppins.style}>
        {/* Next Auth */}
        <SessionProvider>
          {/* Tanstack Query */}
          <QueryClientProvider client={queryClient}>
            {/* Content */}
            <div className="bg-slate-50 flex flex-col scroll-smooth no-scrollbar">
              <MainNavBarLayout>
                {children}
              </MainNavBarLayout>
            </div>
          </QueryClientProvider>
        </SessionProvider>
        <ToastContainer
          position="bottom-right"
          autoClose={5000}
          hideProgressBar
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="colored"
          transition={Bounce}
        />
      </body>
    </html>
  )
}
